### PR TITLE
Fix custom Entry slug on embedded Views (#2207)

### PR DESCRIPTION
**Pull request by doekenorg**
This PR addresses #2207 

When using shortcodes, its hard to determine the correct View for its settings. This PR records the View when the shortcode is being rendered. Based on that value we can now determine the settings correctly. After the shortcode is rendered it forgets the View.

For testing, also test multiple Views on the same page with different Entry slug settings.

💾 [Build file](https://www.dropbox.com/scl/fi/k5dfjawy100618cixj3th/gravityview-2.32-6dcf3f8c1.zip?rlkey=3bpohg1sty1awb594i5yfsdo7&dl=1) (6dcf3f8c1).

### CODE REVIEW

**Comment by doekenorg** [comment]
@Mwalek Please test this one. All the permalink structures should still work.

**Comment by doekenorg** [comment]
> @doekenorg I observed the following issues while testing:
> 
> 1. **Missing "Go Back" Link:** The "Go Back" link occasionally does not appear when viewing a single entry. This can be reproduced by opening different single entries in new tabs multiple times.
> 2. **Custom Page Headings on Single Entry Screens:** Custom page headings are incorrectly displayed on single entry screens, which deviates from the expected behavior.
> 
> Screenshot 2024-11-27 at 3 52 20 PM Screenshot 2024-11-27 at 3 51 46 PM
> 3. **PHP 8.3 Deprecation Warning:** `Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /.../wp-content/plugins/gravityview/future/includes/class-gv-permalinks.php on line 282`
> 
> Screenshot 2024-11-27 at 3 33 13 PM
> 4. **Multiple Entries Displayed on Single Entry Screen:** Occasionally, multiple entries are displayed when opening a single entry.
> 
> ## Steps to Reproduce
> 1. Create two Views, each with a different single entry slug URL.
> 2. Create a new page.
> 3. Add two Heading blocks to the page, each with custom text corresponding to one of the Views.
> 4. Copy the shortcodes for the Views and embed them in the page using Shortcode blocks.
> 5. Publish the page and view it on the front end.
> 6. Click on different single entries and observe the results.
> 
> ## Issue Summary
> * [ ]  "Go Back" link missing when opening single entries in new tabs.
> * [ ]  Custom headings shown on single entry screens.
> * [ ]  PHP 8.3: Deprecated `trim()` warning.
> * [ ]  Multiple entries displayed on single entry screens.

1. I cannot reproduce this at all.
2. Blocks are not connected to the shortcode. If you see a single entry, it should only THAT GravityView shortcode. So it may look weird; But I'm not sure it's wrong. Let's look at it tomorrow together. Or can you create a loom for what you mean, if I don't understand correctly.
3. This should be fixed now
4. Can't reproduce this either. Can you create a loom where this happens?

**Comment by Mwalek** [comment]
@doekenorg, that's strange. I tried in a clean browser and could still replicate the behavior. Could you please try checking the behavior on the URL below and let me know the result?

https://gravityview-pr-2222.try.gravitykit.com/show-views/

**Comment by doekenorg** [comment]
Ok, so 1 issue remains; and I'm not sure thats gonna be an easy fix; or if we need to address this immediately. 

The problem here is that there are multiple views connected to the same form and entries. Every entry get's a single unique ID stored on the entry. If multiple views connect to the same entry; and have different entry slugs, they will keep fighting over the precedence. And a slow DB will cause a timing issue.

This problem is not new to this solution; this problem is already part of GravityView; but it showed itself here because of this particular set up. 

The only solution is to have a new View specific meta key per entry that contains the entry slug for that view, so we can lookup the correct entry based on the combination of the View ID and the slug. This could be a nice addition; but I'm a proponent of adding this as a new feature; and ignore the issue on this PR. 

@mrcasual do you have any thoughts and or objections to that?

**Comment by rafaehlers** [comment]
@doekenorg, is there a slight chance this [other issue ](https://github.com/GravityKit/Social-Sharing/issues/29) in the Social Sharing & SEO extension is related to this limitation you've just found out?

**Comment by doekenorg** [comment]
@rafaehlers No, I don't think they are related.

**Comment by mrcasual** [comment]
> @mrcasual do you have any thoughts and or objections to that?

@doekenorg, sounds reasonable.

**Comment by mrcasual** [comment]
@doekenorg, please create a new issue and feel free to merge this PR.

**Comment by doekenorg** [comment]
New issue is https://github.com/GravityKit/GravityView/issues/2228

**Pull request merged**
