### PR TITLE
Add placeholder in custom searchable fields in search widget

### PR DESCRIPTION
**Pull request by omarkasem**
- Solves https://github.com/GravityKit/GravityView/issues/2113
- It's important for this PR https://github.com/GravityKit/Event-Field/pull/63

💾 [Build file](https://www.dropbox.com/scl/fi/7mxxs1iqaeihv3k22fc03/gravityview-2.27.1-6ab7c3904.zip?rlkey=3xhs7m622m0cga3lw9dqev2hn&dl=1) (6ab7c3904).

### CODE REVIEW

**Comment by mrcasual** [comment]
@mrcasual, please test.

**Comment by mrcasual** [comment]
@Mwalek, please test.

**Comment by Mwalek** [comment]
@mrcasual the placeholders are only visible for "date range" not for dates. Not sure if this is expected or not.

Date (placeholders absent):

Screenshot 2024-08-19 at 3 58 33 PM

Date range (placeholders present):

Screenshot 2024-08-19 at 3 59 21 PM

**Comment by rafaehlers** [comment]
@Mwalek Yes, that's expected! 

@omarkasem All good! Thanks 🙏

**Review by rafaehlers — APPROVED** [review]

**Pull request merged**
