### PR TITLE
Check if value has start and end dates

### PR DESCRIPTION
**Pull request by omarkasem**
- FIxes https://github.com/GravityKit/GravityView/issues/2115
- You can test it with this PR https://github.com/GravityKit/Event-Field/pull/63

💾 [Build file](https://www.dropbox.com/scl/fi/udg5bubiztk0qgoqw7wcu/gravityview-2.27.1-fd80f29b3.zip?rlkey=82pxrbgyelr7wh7999joj2av7&dl=1) (fd80f29b3).

### CODE REVIEW

**Comment by mrcasual** [comment]
@Mwalek, please test.

**Comment by Mwalek** [comment]
@mrcasual I was not able to reproduce the issue without the fix. So I can't confirm that this is fixed.

I tested without the solution and got the following error:

```
<br /><b>Warning</b>:  Illegal string offset ‘start’ in <b>/.../public/wp-content/plugins/gravityview/includes/widgets/search-widget/templates/search-field-date_range.php</b> on line <b>20</b><br />0″>		<input name=
```

After adding the solution (using [this build](https://www.dropbox.com/scl/fi/5luu713a1rrg5my3rywaq/gravityview-2.27.1-cd0027cf8.zip?rlkey=0ptb56dfsj86nmrkddzo7vhl0&dl=1)), the warning no longer appears.

If you can confirm that the problem is the same, then we can consider the issue resolved. Otherwise, please share additional details for reproducing the problem.

✔ Tested on PHP Version 7.4.30.

**Comment by mrcasual** [comment]
@omarkasem, please see @Mwalek's response.

**Comment by rafaehlers** [comment]
I was able to reproduce it:

image

This PR fixed it ✅

**Pull request merged**
