### PR TITLE
[WIP] Fix text-domain error during layout installation

### PR DESCRIPTION
**Pull request by Mwalek**
Issue: https://github.com/GravityKit/GravityView/issues/2110

[Slack discussion](https://gravitykit.slack.com/archives/C04UQME21C7/p1723736648373959).

💾 [Build file](https://www.dropbox.com/scl/fi/r4k7p5vn48oves0o8jbfx/gravityview-2.26-2fe508d6b.zip?rlkey=m1pjxjuq6umc6ovshvn47b0x2&dl=1) (2fe508d6b).

### CODE REVIEW

**Comment by zackkatz** [comment]
Discussion thread here: https://gravitykit.slack.com/archives/C04UQME21C7/p1723736648373959

**Comment by zackkatz** [comment]
@Mwalek Can you please write an issue about the larger issue about the parts of the View editor not refreshing? This PR will fix the issue #2110, but the bigger issue of the states not being in sync needs to be addressed separately.

**Comment by Mwalek** [comment]
Thanks @zackkatz! Here's the new issue:

https://github.com/GravityKit/GravityView/issues/2117

**Comment by mrcasual** [comment]
Partial changes from this PR were merged into `develop` for release, and the PR branch has been rebased.

**Comment by mrcasual** [comment]
Changes were merged into `develop` for release. https://github.com/GravityKit/GravityView/issues/2117 will be addressed in a separate PR.

**Pull request closed without merging**
