### PR TITLE
Issue/2086 edit entry doesnt respect file uploads maximum number of files setting2

### PR DESCRIPTION
**Pull request by omarkasem**
- Fixes https://github.com/GravityKit/GravityView/issues/2086#issuecomment-2329849158
- Button is disabled now after maximum files is reached
- Maximum number error message is shown if maximum files is more than 1
- Fixed an extra issue where if you have multi upload file with max 3 files, Then you upload all 3 files in the edit entry page and then after the edit you remove one file and try to upload a different file, it doesn't register that new file and shows a message that the maximum is reached.

💾 [Build file](https://www.dropbox.com/scl/fi/tg5yljzjyjjritbskillh/gravityview-2.28.0-572e0fa02.zip?rlkey=mkze7xj5om0xnq8010fzd0pt8&dl=1) (572e0fa02).

### CODE REVIEW

**Comment by mrcasual** [comment]
@Mwalek, please test.

**Comment by Mwalek** [comment]
@omarkasem @mrcasual  The solution is working. The only problem is that the max number of files reached warning was shown more than once when uploading 3 files at the same time. View recordings below for reference:

https://www.loom.com/share/dee3ad3d9056435faa5dc22a18276d2e?sid=72711aa2-04fd-45e6-a60f-d284e4b039c2

https://www.loom.com/share/8a9042f1b1e4484cb12e5670a0435de7?sid=67164fee-39fa-4dfe-b6ae-67de8a9eeb5d

**Comment by rafaehlers** [comment]
@Mwalek Thanks for the videos! What happens when you remove one of the files, does the upload button functionality works again/restores its functionality?

**Comment by omarkasem** [comment]
@Mwalek Thanks for catching that, It's fixed now with the latest commit.

**Comment by Mwalek** [comment]
@omarkasem the latest commit fixes the multiple warnings issue. I've uploaded videos highlighting the results.

However, I noticed a new problem. In the second video, the maximum number of files warning is not shown after deleting a file and adding a new one. It is also possible to add more than one file, which causes an error when saving the entry.

@rafaehlers the second video should answer your question. Let me know, thanks.

1. https://www.loom.com/share/68be5e6f6e504f6688286deacf50377e
2. https://www.loom.com/share/8aa4d68584a54afbae7ae78148338cd2

**Comment by omarkasem** [comment]
@Mwalek Thanks for noticing that, I fixed it now with the latest commit.

**Comment by Mwalek** [comment]
@omarkasem the solution [looks good](https://www.loom.com/share/6728aa629ae14cccadadf60f24339e74?sid=9cba2b3a-425c-42bf-aaed-c7b67476c0e4), thank you!

NB: The deprecation warning shown in my loom recording can be ignored because it was [fixed here](https://github.com/GravityKit/GravityView/issues/2134).

**Comment by mrcasual** [comment]
@Mwalek, was this fully tested?

**Comment by Mwalek** [comment]
@mrcasual yes, testing was completed.

**Pull request merged**
