### PR TITLE
Feature/1921 layout builder

### PR DESCRIPTION
**Pull request by doekenorg**
This PR addresses #1921.

I've taken a free interpretation of the designs in Figma, to keep progress up. 

Currently it only focusses on Widgets. 

- [x] Some extra styling
- [x] Multiple Forms button styling
- [x] Add support for fields (letting templates opt-in; DIY by default?) 
- [x] Global opt-in setting to this behaviour (?)

💾 [Build file](https://www.dropbox.com/scl/fi/aa8kibp5utw4ry09ko0fd/gravityview-2.30.1-59fe66296.zip?rlkey=f7m2vyw7s9dlu1d4p88rn23jn&dl=1) (59fe66296).

### CODE REVIEW

**Comment by Mwalek** [comment]
While doing preliminary testing of this PR I encountered 2 issues.

**Issue 1: Custom Content in Top Widget Row Disappears**

Custom content added to the top widget row is lost unless paired with a different widget (e.g., the search widget).

**Steps to Reproduce:**
1. Delete all rows in the top widget area.
2. Create a custom row with 2 columns.
3. Add the "Custom Content" widget to both columns and input content.
4. Save the View.

After the page refreshes, the custom content disappears.

**Issue 2: Unable to Add Rows Without Saving the View First**

Let me know if you have any questions :)

**Issue Summary**
- [ ] Custom Content in Top Widget Row Disappears
- [ ] Unable to Add Rows Without Saving the View First

**Comment by doekenorg** [comment]
@Mwalek @crbdev This is officially ready for full testing. Please include the Layout Builder Template as well. You can find that on the Release Manager.

Casey, I'm tagging you to check if this is (at least good) enough for your demo on Oct 28th.

**Comment by Mwalek** [comment]
@doekenorg there is still an issue when clicking the "Add row" button under Entries Fields before saving the View. Additionally, you may want to use uppercase "Row" to match the "Add Field" button.

- [ ] Unable to Add Rows Without Saving the View First under Entries Fields
- [ ] Change "Add row" to Title Case (Add Row)

**Comment by doekenorg** [comment]
@Mwalek fixed those.

**Comment by Mwalek** [comment]
@doekenorg thanks, I confirmed the fixes!

**Comment by crbdev** [comment]
It appears that the "Go back" link is missing. When you go to the Single Entry page, there is no link to go back to the Multiple Entries page. @Mwalek Do you see this too?

**Comment by Mwalek** [comment]
@crbdev I can't reproduce with build 0a24db8. You can see my test here:

https://basecamp.try.gravitykit.com/collection/lorem-3/item/item-26/

Feel free to create your own tests and change plugin versions on the site.

**Comment by Mwalek** [comment]
@crbdev that's the same build that I used, no? 🤔

**Pull request merged**
