### PR TITLE
Issue/1978 add merge tags now today yesterday

### PR DESCRIPTION
**Pull request by omarkasem**
- Fixes https://github.com/GravityKit/GravityView/issues/1978
- Added merge tags now, yesterday and tomorrow
- Made them work with format and timestamp
- Added unit tests 

💾 [Build file](https://www.dropbox.com/scl/fi/sc7axiegitbfq4c7vc3e4/gravityview-2.28.0-97f835136.zip?rlkey=ve9h5c8g17e8mgb291plfnuta&dl=1) (97f835136).

### CODE REVIEW

**Comment by mrcasual** [comment]
@Mwalek, please test and ensure that it works properly with different timezones.

**Comment by Mwalek** [comment]
@omarkasem @mrcasual

- The merge tags all work, but I noticed that "now" shows the same value as "today." I'm unsure if this is expected.

Screenshot 2024-09-17 at 4 45 38 PM

- The 'now', 'today', and 'yesterday' merge tags don't appear in the merge tag dropdown or search.

Screenshot 2024-09-17 at 5 12 04 PM

- When the timezone is changed, the values for the 'now', 'today', and 'yesterday' merge tags are correct.
- However, the timestamp modifier doesn't work correctly with timezones other than UTC/GMT. A UNIX timestamp is independent of timezones, so changing the timezone shouldn't affect the result. For example, when set to UTC+2, the time is incorrectly ahead by 2 hours.

Screenshot 2024-09-17 at 4 58 53 PM

- The format modifier works as expected (even with different timezones).

Screenshot 2024-09-17 at 5 04 52 PM

### Summary of Issues:
- [ ] "Now" and "today" show the same value.
- [ ] 'Now', 'today', and 'yesterday' merge tags are missing from the dropdown/search.
- [ ] Timestamp modifier shows incorrect results for timezones other than UTC/GMT.

Test URL: https://gv-issue-2143.try.gravitykit.com/display-m-tag-view/ (test:test)

**Comment by rafaehlers** [comment]
Should `now` output `yyyy-mm-dd hh:mm:ss`?

Also, the default output of `today` and `yesterday` should be a formatted date that can be used inside the Advanced Filters and/or `[gvlogic]` shortcode. @Mwalek did you test them on AF and `[gvlogic]`? If not, please do! 

We need to be able to work on these conditions: https://docs.gravitykit.com/article/446-highlighting-entries-about-to-expire

**Comment by omarkasem** [comment]
@Mwalek @rafaehlers 
1- The new tags act the same way as the today tag, so if you want to get the full value then you have to do {now:raw}
That the same thing that happens with today and date_updated etc..
2- I don't think we have to add them to the dropdown like gf does with today
3- I don't understand this one, What do you mean by unix timestamp? It works when i change the timezone in wordpress settings, how can i test that unix timestamp so i can test it?

I also tested it with gvlogic with now:timestamp and it worked

**Comment by Mwalek** [comment]
@omarkasem 

1. Thanks for clarifying. `{now:raw}` works. Example output: `2024-09-19 00:46:11`
2. Noted.
3. Please make reference to the following video: https://www.loom.com/share/328d3a93bb25402fbecad93769441832?sid=42d4aa6f-028c-44c9-bca6-c02bb8bb3554

@rafaehlers I'm still testing AF, but I can confirm that the new merge tags work with `[gvlogic]`. E.g:

```
[gvlogic if="{Due Date:3:mdy}" less_than="{today:format:m/d/Y}"]
	<span class="gk-task gk-task-expired">Expired</span>
[/gvlogic]

[gvlogic if="{Due Date:3:mdy}" is="{today:format:m/d/Y}"]
	<span class="gk-task gk-task-expiring-soon">Expiring Soon</span>
[/gvlogic]

[gvlogic if="{Due Date:3:mdy}" greater_than="{today:format:m/d/Y}"]
	<span class="gk-task gk-task-on-time">On Time</span>
[/gvlogic]
```

**Comment by omarkasem** [comment]
@Mwalek Thanks for the detailed video, That's fixed now with the latest commit

**Comment by Mwalek** [comment]
Thanks @omarkasem!

@rafaehlers Do you want to propose any changes before I proceed to test the latest commit?

**Comment by mrcasual** [comment]
@rafaehlers, please see @Mwalek's [comment](https://github.com/GravityKit/GravityView/pull/2143#issuecomment-2360423631).

**Comment by rafaehlers** [comment]
No, that's it, we're good @Mwalek 👍

**Comment by Mwalek** [comment]
@omarkasem using 97f8351, the Advanced Filters "Add Condition" button doesn't show up, could you check?

### Steps to Reproduce
1. Install and activate 97f8351
2. Install and activate Advanced Filters
3. Create a NEW View
4. Visit the Filter & Sort Tab

**Expected**: The _Add Condition_ button should be visible.

**Actual**: The _Add Condition_ button is not visible.

Loom Video: https://www.loom.com/share/9d0bcd646a7c48958924e29e2c63ec81?sid=6f03f44a-3e20-403c-b4c9-49642625b356

**Comment by mrcasual** [comment]
@Mwalek, was this fully tested?

**Pull request merged**
