### PR TITLE
Add human modifier for date and time fields

### PR DESCRIPTION
**Pull request by omarkasem**
- FIxes https://github.com/GravityKit/GravityView/issues/1990
- I had to edit the `GravityView_Field_Date` class because it was overriding the human modifier by running the function again without the new arguments and i couldn't remove the filter `gravityview/merge_tags/modifiers/value` as it was happening after the human modifier function.

💾 [Build file](https://www.dropbox.com/scl/fi/55s0yfg7q7x5h663r349q/gravityview-2.28.0-cb02ebddc.zip?rlkey=nmffl5isaq265aj4fzxsel67g&dl=1) (cb02ebddc).

### CODE REVIEW

**Comment by mrcasual** [comment]
@omarkasem, looks good, thanks. Could you please add a unit test for this?

**Comment by Mwalek** [comment]
@mrcasual I think there is a problem with the handling of future dates (see image).

Screenshot 2024-09-05 at 7 52 53 PM

Try site: https://diy-issue-248964a.try.gravitykit.com/display-human/

**Comment by mrcasual** [comment]
@Mwalek, could it be due to the difference between the site's timezone and your local time?

CleanShot 2024-09-05 at 14 48 30@2x

**Comment by omarkasem** [comment]
@Mwalek Thanks for noticing, It's fixed now.
@mrcasual I also added extra tests for future dates and times.

**Comment by mrcasual** [comment]
@Mwalek, please retest and also try with different timezones.

**Comment by Mwalek** [comment]
@omarkasem @mrcasual future dates are now displayed correctly.

As for the timezone, it doesn't matter what is set in WordPress (settings > general), it looks like the server timezone (UTC) is employed. This applies to both comparisons of past and future dates.

In the image below, I have the WordPress timezone set to UTC+2, my timezone, so if the human time difference were applying this setting, I would expect to see the next day starting in 2 hours instead of 4 (see image).

Screenshot 2024-09-08 at 10 01 28 PM

**Comment by mrcasual** [comment]
@omarkasem, you may find this relevant: https://github.com/GravityKit/GravityView/commit/2850c35eee29f44e49d84167c72704296e44598c.

**Comment by mrcasual** [comment]
@omarkasem, please see comments above.

**Comment by omarkasem** [comment]
@Mwalek Thanks for the detailed comment, I think the last commit fixed the timezone issue.

**Comment by Mwalek** [comment]
@omarkasem @mrcasual I confirmed that the timezone issue is fixed in the latest commit.

**Pull request merged**
