### PR TITLE
Integrate with LifterLMS

### PR DESCRIPTION
**Pull request by zackkatz**
This was done in July 2020. Let's improve it and release!

### Testing instructions

1. Install LifterLMS from Plugins > Add New
2. Do their onboarding, add placeholder content
3. [Go to LifterLMS > Settings](https://i.gravitykit.com/i/jXUdXE)
4. Click on the Integrations tab
5. Click on GravityView
6. Enable the integration
7. Choose which Views to show
8. Click Save Changes
9. Go to Pages and find the Dashboard page created during onboarding
10. View the page

**What you should see:**

- You should [see "My Forms" in the navigation](https://i.gravitykit.com/i/9mACym)
- Clicking on My Forms shows the Views, embedded

11. Now, go back to LifterLMS GravityView settings
12. Change "My Forms" label to "My Views"
13. Confirm that the label in the nav changed

### Issues

- [x] I needed to re-save permalinks before this worked

### CODE REVIEW

**Comment by crbdev** [comment]
I've tested this and it works! However, it seems Views aren't rendering properly on the dashboard page. 

Business directory View on LifterLMS dashboard:

CleanShot 2024-02-23 at 13 00 12@2x

Same View embedded on regular page:

CleanShot 2024-02-23 at 12 59 51@2x

**Comment by zackkatz** [comment]
@crbdev I fixed the CSS issue; please test again.

**Comment by zackkatz** [comment]
- [ ] Single entry links aren't working for DataTables

@mrcasual Do you have any idea for how to do [this override](https://github.com/GravityKit/GravityView/pull/1882/commits/722f6bf69eb5bef8ebaf596e40b114b0b9bafd97) in DataTables? 

Here's a video where I discuss why this is more complex than I wanted it to be: https://www.loom.com/share/3bd8f377427949cc9c1dd5b89031e024

**Comment by crbdev** [comment]
@zackkatz I tested again and found the following issue: CSS and JS code added to the "Custom Code" box in the View settings is not being executed for Views on the LifterLMS dashboard.

**Comment by zackkatz** [comment]
Good catch!

**Comment by zackkatz** [comment]
@crbdev It works for me. Can you provide more steps to reproduce?

**Comment by crbdev** [comment]
https://prudent-macaw-b4fadd.try.gravitykit.com/wp-login.php
GravityKitDemo
2x9npZCK0hvEfOSJjwaW 

Here is the LifterLMS dashboard page. See that the heading and subheading are visible, and so is the text that reads "TEST TEXT!!!"
https://prudent-macaw-b4fadd.try.gravitykit.com/dashboard/my-forms/

Here is the same View embedded on a regular page. See that the heading and subheading are hidden using CSS. The "TEST TEXT!!!" is hidden with JS.
https://prudent-macaw-b4fadd.try.gravitykit.com/business-directory-2/

**Comment by zackkatz** [comment]
I used GravityMigrate to export this View and import it into a local site. It works there. Going to continue to debug.

**Comment by zackkatz** [comment]
@crbdev When you're back at work, please test again.

**Comment by crbdev** [comment]
@zackkatz I'm testing with the latest build in Release Manager. JS is now being executed properly, but the CSS is not.

**Pull request merged**
