### PR TITLE
Issue/1894 better support for checkbox field

### PR DESCRIPTION
**Pull request by omarkasem**
Both should be merged together to fully work
https://github.com/GravityKit/GravityEdit/pull/240

### CODE REVIEW

**Comment by zackkatz** [comment]
@omarkasem The tests here are failing. Please fix.

```
There were 2 errors:

1) GVFuture_Test::test_frontend_field_html_checkbox
Undefined array key "choice_display"

*********************/templates/fields/field-checkbox-html.php:27
/tmp/wordpress-develop/src/wp-includes/template.php:787
*********************/future/lib/class-gamajo-template-loader.php:262
*********************/future/lib/class-gamajo-template-loader.php:120
*********************/future/includes/class-gv-template-field.php:314
*********************/future/includes/class-gv-renderer-field.php:61
*********************/tests/unit-tests/GravityView_Future_Test.php:2801

2) GVFuture_Test::test_frontend_field_html_product
Undefined array key "choice_display"

*********************/templates/fields/field-checkbox-html.php:27
/tmp/wordpress-develop/src/wp-includes/template.php:787
*********************/future/lib/class-gamajo-template-loader.php:262
*********************/future/lib/class-gamajo-template-loader.php:120
*********************/future/includes/class-gv-template-field.php:314
*********************/future/includes/class-gv-renderer-field.php:61
*********************/tests/unit-tests/GravityView_Future_Test.php:4316
```

**Comment by omarkasem** [comment]
@zackkatz It's fixed now with the latest commit

**Comment by zackkatz** [comment]
@rafaehlers Please test

**Comment by rafaehlers** [comment]
@zackkatz @mrcasual this works! Let's merge.

**Pull request merged**
