### PR TITLE
Select different layouts for multiple and single entry (per-context switcher)

### PR DESCRIPTION
**Pull request by doekenorg**
## Things to test:

- [x] Saving existing Views shouldn't change anything
  - Edit an existing View
  - Don't do anything
  - Save the View
  - Check to make sure the previous single/multiple entries layouts don't change
- [x] Updating a View works
  - Edit an existing View
  - Change the layout type
  - Save the View
  - Confirm that the layouts are correct for single & multiple layouts
- [x] Confirm that the View type change dialog occurs when switching from Table/DataTables to other layouts
- [x] Confirm that when changing layout types and the fields are cleared, only the current tab is affected

### Testing different states
- Unlicensed or license doesn't support layouts
  - [x] Should show "Available in Pro" button
  - [x] Items should [look like the design](https://www.figma.com/file/OM63Lq6eIlzu3nFPR4Xro8/GravityKit-UI%2FUX?type=design&node-id=2851-1934&mode=design&t=kHZnBwMUU83JZgEr-0)
- Has license but layout is not installed
  - Should [look like design](https://www.figma.com/file/OM63Lq6eIlzu3nFPR4Xro8/GravityKit-UI%2FUX?type=design&node-id=2851%3A107&mode=design&t=kHZnBwMUU83JZgEr-1)
  - [x] Clicking the Install Now button should install and activate the layout plugin
  - [x] The layout should then appear clickable
  - [x] Clicking the newly-installed layout should activate it
- Has license and layout is installed, but not activated
  - [x] Clicking Activate should activate the layout plugin
  - [x] The layout should then appear clickable
  - [x] Clicking the newly-installed layout should activate it

### Browser test

Check appearance, confirm functionality in:

- [ ] Chrome
- [ ] Firefox
- [ ] Safari

-------

This PR addresses #1177. 

It adds a new dropdown solution with support for icons and descriptions. It also adds a new variable that contains a separate template for the single entry. There is backwards compatibility as the value of the new variable has a fallback to the "old" variable, that is now solely for the multiple entries.

pr-preview

Todo: 
- [x] It needs a design (and fixes) for inactive items like the regular selection now has.
- [x] It needs icons for native templates, otherwise fallback to the image it now has.

In the meantime this can be tested and reviewed for what we have now. 

image

💾 [Build file](https://www.dropbox.com/scl/fi/zkz7kc5lu38n3f2m3bqj3/gravityview-2.23-18613244e.zip?rlkey=2i9n51967fewbpdeagd15n6wa&dl=1) (18613244e).

### CODE REVIEW

**Comment by zackkatz** [comment]
Hey @doekenorg, I had a chance to review. I found a few issues:

- [ ] As we discussed, please only show layouts, not presets, in the dropdown
- [ ] There are some strange CSS issues going on for me, including inner scrollbars and modals not being visible. I imagine these are just a matter of scoping the dropdown toggle. [Please check out the video](https://www.loom.com/share/a592c3505f5c442db97fb9c75583af5b). [Video two shows](https://www.loom.com/share/4200753fde93445f92756447eaa0e92f) that it's not the `_view-dropdown.scss` file?
- [ ] When the dropdown is open, clicking outside of it should close the dropdown

Thanks 👍

**Comment by zackkatz** [comment]
@doekenorg Hey, can you please update to [the new designs](https://www.figma.com/file/OM63Lq6eIlzu3nFPR4Xro8/GravityKit-UI%2FUX?type=design&node-id=1117-4203&mode=design&t=cRXODAMDK26kGEwJ-11)?

**Comment by crbdev** [comment]
Here are my notes from testing this PR. Besides the issues highlighted below and the things not yet tested, everything else works well.

**1. Updating existing Views and creating new Views**

Using the combination of DataTabls Table for the MEL and List for the SEL causes a warning message to appear when navigating to the SEL on the front end: "The Single Entry layout has not been configured".

Steps to reproduce:

- Create a new View
- Select the DataTables Table View Type
- Go to the SIngle Entry Layout tab
- Use the View switcher to change the layout to "List"
- Add fields to the SIngle Entry Layout
- Save the View and view on front-end.

*This also happens when editing an existing View
*I didn't enounter any issues with other layout combinations 

**2. Installing or activating layouts from inside the View switcher** 

To be clear, this works! I only have a suggestion. When installing or activating layouts, there is a spinner on the cursor while the layout is installed or activated. However, this spinner disappears if you hover over another layout choice. Other layouts are still clickable while this is happening. So, if you move your cursor, it's not clear that anything is actually happening. Maybe we should make it more clear that something is happening, and/or not have the other layouts clickable while this is process is occuring?

**3. The Maps (Default) layout)**

Possibly another discussion but I wonder if we want the Maps layout available at all? After all, it is most useful as a widget. Moreover, for the Single Entry Layout, the "Maps (Default)" options is the same as the List layout as far as I can tell, so we could consider removing it as an option there?

**Things not tested**

* Has license and layout is installed, but not activated
    * Clicking Activate should activate the layout plugin
    * The layout should then appear clickable
    * Clicking the newly-installed layout should activate it

**Comment by doekenorg** [comment]
- [x] Unlicensed support
Scherm­afbeelding 2024-05-09 om 13 56 42

- [x] Spinner loading state
spinner

**Comment by zackkatz** [comment]
@doekenorg Here's a video showing [what Casey wrote](https://github.com/GravityKit/GravityView/pull/1996#issuecomment-2089652506).

https://www.loom.com/share/012f831a2579436d9d4ed705d4e9361b

**Comment by doekenorg** [comment]
> @doekenorg Here's a video showing [what Casey wrote](https://github.com/GravityKit/GravityView/pull/1996#issuecomment-2089652506).
> 
> https://www.loom.com/share/012f831a2579436d9d4ed705d4e9361b

Sorry, I forgot to mention, but you need https://github.com/GravityKit/DataTables/pull/221 this Datatables plugin to fix that :-)

**Comment by zackkatz** [comment]
We need to remove the `#gv_switch_view_button` button from the Data Source menu.

[It's in `admin-views.js`](https://github.com/GravityKit/GravityView/blob/bb69f405c5f98541d0c5dce768c9ad088d185022/assets/js/admin-views.js#L138) in multiple places.

**Comment by doekenorg** [comment]
@zackkatz what do you mean with: `Make sure it works with View Presets` ?

**Comment by rafaehlers** [comment]
- [ ] Update the word `view` in this link to `View` and change the target URL to: https://docs.gravitykit.com/article/400-what-are-the-differences-between-the-view-types
image

**Comment by crbdev** [comment]
- [ ] Add UTM tracking links to all "Buy Now" buttons

Here's what I would propose, as an example:
`/?utm_campaign=gk_upsells&utm_source=view-editor&utm_content=diy`

UTM sheet for reference
https://docs.google.com/spreadsheets/d/15oBygotBeX1TT_5Q-5L9Eslmh8EyWrqU1hn-6CT1i34/edit#gid=0

**Comment by doekenorg** [comment]
> * [ ]  Add UTM tracking links to all "Buy Now" buttons
> 
> Here's what I would propose, as an example: `/?utm_campaign=gk_upsells&utm_source=view-editor&utm_content=diy`
> 
> UTM sheet for reference https://docs.google.com/spreadsheets/d/15oBygotBeX1TT_5Q-5L9Eslmh8EyWrqU1hn-6CT1i34/edit#gid=0

@crbdev I changed it to `https://www.gravitykit.com/pricing/?utm_campaign=gk_upsells&utm_source=view-editor&utm_content=upgrade` because the upgrades are combined into a new section with a single "upgrade" button. Is that ok?

**Comment by doekenorg** [comment]
Found a bug: 

- [ ] Storing the view can cause a js error that triggers a weird warning in the page.

**Comment by crbdev** [comment]
On the "Views" page, the "Template" column only shows the layout being used on the multiple entry page, should we update this to reflect the layout being used on both the multiple and single entry pages? 

e.g. 👇 

CleanShot 2024-05-27 at 10 30 12@2x

**Comment by doekenorg** [comment]
@crbdev  done 
image

**Pull request merged**
