### PR TITLE
Adds initials modifier, Fixes array raw value for merge tags and Make…

### PR DESCRIPTION
**Pull request by omarkasem**
- Implements https://github.com/GravityKit/GravityView/issues/2156
- Adds initials modifier
- Fixes array raw value for merge tags
- Makes convert to initials function to use in multiple places

💾 [Build file](https://www.dropbox.com/scl/fi/rw44rjoceype7vsi03ruo/gravityview-2.30.1-558665ad9.zip?rlkey=3zbenbxsaf18rf60td9vcpkoe&dl=1) (558665ad9).

### CODE REVIEW

**Comment by Mwalek** [comment]
@omarkasem I noticed that the `initials` modifier works for all text and number fields, is this intended?

**Comment by mrcasual** [comment]
@omarkasem, please see @Mwalek's comment.

**Comment by omarkasem** [comment]
@Mwalek Should i make it only work for name fields?

**Comment by Mwalek** [comment]
@omarkasem I don't know. @mrcasual @rafaehlers should the initials modifier work for all text and number fields?

**Comment by rafaehlers** [comment]
I don't see this as a problem if it works for text inputs and number fields, although I have no idea how this can be used in a number field. 🤔 

Let's leave it like that if it's ready.

**Pull request merged**
